<?php

namespace App\Console\Commands;

use Illuminate\Support\Str;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Schema;

class MakeCrud extends Command
{
    protected $signature = 'make:crud {schema} {--drop-all}';
    protected $description = 'Generate migration, model, controller, and views based on a JSON schema';

    public function handle()
    {
        try {
            $schemaPath = storage_path('app' . DIRECTORY_SEPARATOR . 'schemas' . DIRECTORY_SEPARATOR . $this->argument('schema') . '.json');
            if (!File::exists($schemaPath)) {
                $this->error('Schema file not found at ' . $schemaPath);
                Log::error('Schema file not found: ' . $schemaPath);
                return 1;
            }

            $schema = json_decode(File::get($schemaPath), true);
            if (json_last_error() !== JSON_ERROR_NONE) {
                $this->error('Invalid JSON schema: ' . json_last_error_msg());
                Log::error('Invalid JSON schema: ' . json_last_error_msg());
                return 1;
            }

            $model = $schema['model'] ?? null;
            $table = $schema['table'] ?? null;
            $fields = $schema['fields'] ?? [];
            $timestamps = $schema['timestamps'] ?? true;

            if (!$model || !$table || empty($fields)) {
                $this->error('Invalid schema: model, table, or fields missing');
                Log::error('Invalid schema: model, table, or fields missing');
                return 1;
            }

            // Add label translations early so they're ready for views
            $this->updateLabelTranslations($fields);

            // DELETE all previous CRUD files before generating again
            //if ($this->confirm('Do you want to refresh the all files from generated by CRUD commad? This will delete all files.', true)) {
            $this->deleteCrudFiles($model, $table);
            //}

            // Generate Migration
            if (!$this->generateMigration($model, $table, $fields, $timestamps)) {
                return 1;
            }

            // Run Migration
            if ($this->confirm("Do you want to refresh the '{$table}' table? This will delete and re-migrate only that table.", true)) {
                $this->info("Refreshing '{$table}' table...");

                // Drop only the specific table
                Schema::disableForeignKeyConstraints();
                Schema::dropIfExists($table);
                Schema::enableForeignKeyConstraints();
                $this->info("Dropped '{$table}' table.");

                // Find and run its migration file
                $migrationFile = collect(File::files(database_path('migrations')))
                    ->first(fn($file) => str_contains($file->getFilename(), "create_{$table}_table"));

                if ($migrationFile) {
                    Artisan::call('migrate', [
                        '--path' => 'database/migrations/' . $migrationFile->getFilename(),
                        '--force' => true,
                    ]);
                    $this->info("Migration for '{$table}' ran successfully.");
                    $this->info(Artisan::output());
                } else {
                    $this->warn("Migration file for '{$table}' not found.");
                }
            }

            // Generate Model
            if (!$this->generateModel($model, $fields)) {
                return 1;
            }

            // Generate Store Request
            if (!$this->generateRequest($model, $fields, 'Store')) {
                return 1;
            }

            // Generate Update Request
            if (!$this->generateRequest($model, $fields, 'Update')) {
                return 1;
            }

            // Generate Controller
            if (!$this->generateController($model, $fields)) {
                return 1;
            }

            // Generate Views
            if (!$this->generateViews($model, $table, $fields)) {
                return 1;
            }

            // Append Routes (after controller is generated)
            if (!$this->appendRoutes($model, $table)) {
                return 1;
            }

            // Generate Seeder
            if (!$this->generateSeeder($model, $fields)) {
                return 1;
            }

            // Run Seeder
            Artisan::call('db:seed', [
                '--class' => $model . 'Seeder',
                '--force' => true,
            ]);

            $this->info("CRUD for {$model} generated successfully!");
            return 0;
        } catch (\Exception $e) {
            $this->error('An error occurred: ' . $e->getMessage());
            Log::error('MakeCrud failed: ' . $e->getMessage(), ['exception' => $e]);
            return 1;
        }
    }

    protected function updateLabelTranslations($fields)
    {
        $labelsPath = resource_path('lang/en/labels.php');

        // Load existing labels or initialize
        $labels = file_exists($labelsPath) ? include $labelsPath : [];

        if (!is_array($labels)) {
            $labels = [];
        }

        // Add new labels
        foreach ($fields as $field) {
            $name = $field['name'];
            if (!isset($labels[$name])) {
                $labels[$name] = ucfirst(str_replace('_', ' ', $name));
            }
        }

        // Convert array to valid PHP
        $labelExport = "<?php\n\nreturn " . var_export($labels, true) . ";\n";
        File::put($labelsPath, $labelExport);
    }

    protected function deleteCrudFiles($model, $table)
    {
        $this->info("Deleting existing files for {$model}...");

        $modelFile = app_path("Models/{$model}.php");
        if (File::exists($modelFile)) {
            File::delete($modelFile);
            $this->info("Deleted model: {$modelFile}");
        }

        $controllerFile = app_path("Http/Controllers/{$model}Controller.php");
        if (File::exists($controllerFile)) {
            File::delete($controllerFile);
            $this->info("Deleted controller: {$controllerFile}");
        }

        // Delete views directory
        $viewsDir = resource_path('views/' . \Illuminate\Support\Str::snake($model));
        if (File::exists($viewsDir)) {
            File::deleteDirectory($viewsDir);
            $this->info("Deleted views directory: {$viewsDir}");
        }

        // Delete migration files for this table (all matching *create_<table>_table.php)
        $migrationFiles = glob(database_path("migrations/*_create_{$table}_table.php"));
        foreach ($migrationFiles as $migration) {
            File::delete($migration);
            $this->info("Deleted migration: {$migration}");
        }

        // Remove route entry from routes/web.php
        $routesFile = base_path('routes/web.php');
        if (File::exists($routesFile)) {
            $routesContent = File::get($routesFile);
            $routeLine = "Route::resource('{$table}', {$model}Controller::class);";

            // Remove the route line and the possible "use" statement line above it
            $pattern = '/(\n?use\s+App\\\\Http\\\\Controllers\\\\' . preg_quote($model, '/') . 'Controller;\n)?\s*' . preg_quote($routeLine, '/') . '\n?/';

            $newContent = preg_replace($pattern, '', $routesContent);
            if ($newContent !== $routesContent) {
                File::put($routesFile, $newContent);
                $this->info("Removed route entry from routes/web.php");
            }
        }

        // Remove label entry from resources/lang/en/labels.php
        $this->removeLabelFromLangFile($model);
    }

    protected function removeLabelFromLangFile($model)
    {
        $labelsFile = resource_path('lang/en/labels.php');

        if (!File::exists($labelsFile)) {
            $this->warn("labels.php not found.");
            return;
        }

        $labels = include $labelsFile;
        $key = Str::snake($model);

        if (!is_array($labels)) {
            $this->error("labels.php is not an array.");
            return;
        }

        if (!array_key_exists($key, $labels)) {
            $this->info("No label entry found for '{$key}' in labels.php.");
            return;
        }

        unset($labels[$key]);

        $exported = "<?php\n\nreturn " . var_export($labels, true) . ";\n";
        File::put($labelsFile, $exported);

        $this->info("Removed '{$key}' entry from labels.php.");
    }

    protected function appendRoutes($model, $table)
    {
        try {
            // Check if route already exists to avoid duplicates
            $webRoutes = File::get(base_path('routes/web.php'));
            $routeString = "Route::resource('{$table}', {$model}Controller::class);";
            if (strpos($webRoutes, $routeString) !== false) {
                $this->info("Route for {$table} already exists, skipping append");
                return true;
            }

            $routeContent = "\nuse App\\Http\\Controllers\\{$model}Controller;\n{$routeString}\n";
            File::append(base_path('routes/web.php'), $routeContent);
            $this->info("Routes appended for {$model}");
            return true;
        } catch (\Exception $e) {
            $this->error('Failed to append routes: ' . $e->getMessage());
            Log::error('Failed to append routes: ' . $e->getMessage(), ['exception' => $e]);
            return false;
        }
    }

    protected function generateMigration($model, $table, $fields, $timestamps)
    {
        try {
            $migrationName = 'create_' . $table . '_table';
            $this->call('make:migration', ['name' => $migrationName]);

            // Find the latest migration file (since timestamp may vary slightly)
            $migrationFiles = glob(database_path('migrations/*_' . $migrationName . '.php'));
            if (empty($migrationFiles)) {
                $this->error('Migration file not created');
                Log::error('Migration file not created for ' . $migrationName);
                return false;
            }
            $migrationPath = end($migrationFiles); // Get the latest file

            if (!File::exists(base_path('stubs/migration.create.stub'))) {
                $this->error('Migration stub not found');
                Log::error('Migration stub not found at stubs/migration.create.stub');
                return false;
            }

            $stub = File::get(base_path('stubs/migration.create.stub'));

            $fieldsContent = '';
            foreach ($fields as $field) {
                $type = $field['type'] ?? 'string';
                $name = $field['name'] ?? null;
                $nullable = $field['nullable'] ? '->nullable()' : '';
                $length = isset($field['length']) ? ", {$field['length']}" : '';
                $precision = isset($field['precision']) ? ", {$field['precision']}, {$field['scale']}" : '';

                if (!$name) {
                    $this->error('Field name missing in schema');
                    Log::error('Field name missing in schema');
                    return false;
                }

                if ($type == 'decimal') {
                    $fieldsContent .= "\$table->$type('$name'$precision)$nullable;\n            ";
                } else {
                    $fieldsContent .= "\$table->$type('$name'$length)$nullable;\n            ";
                }
            }

            if ($timestamps) {
                $fieldsContent .= "\$table->timestamps();\n            ";
            }

            $stub = str_replace(['{{ table }}', '{{ fields }}'], [$table, $fieldsContent], $stub);
            File::put($migrationPath, $stub);
            $this->info("Migration generated for {$table}");
            return true;
        } catch (\Exception $e) {
            $this->error('Failed to generate migration: ' . $e->getMessage());
            Log::error('Failed to generate migration: ' . $e->getMessage(), ['exception' => $e]);
            return false;
        }
    }

    protected function generateModel($model, $fields)
    {
        try {
            $this->call('make:model', ['name' => $model]);

            $modelPath = app_path("Models/{$model}.php");
            if (!File::exists($modelPath)) {
                $this->error("Model file not created at {$modelPath}");
                return false;
            }

            $stub = File::get($modelPath);

            // Fillable
            $fillable = collect($fields)
                ->pluck('name')
                ->map(fn($name) => "'$name'")
                ->implode(', ');
            $fillableLine = "    protected \$fillable = [{$fillable}];\n\n";

            // Casts
            $castsArray = collect($fields)
                ->filter(fn($field) => in_array($field['type'], ['date', 'datetime', 'boolean', 'json', 'array']))
                ->mapWithKeys(fn($field) => [
                    $field['name'] => match ($field['type']) {
                        'date' => 'date',
                        'datetime' => 'datetime',
                        'boolean' => 'boolean',
                        'json', 'array' => 'array',
                        default => null,
                    }
                ])
                ->filter();

            $castsLine = '';
            if ($castsArray->isNotEmpty()) {
                $castsString = $castsArray
                    ->map(fn($type, $name) => "        '$name' => '$type'")
                    ->implode(",\n");

                $castsLine = "    protected \$casts = [\n{$castsString}\n    ];\n\n";
            }

            // Relationships
            $schemaPath = storage_path('app/schemas/' . strtolower($model) . '.json');
            $schema = File::exists($schemaPath) ? json_decode(File::get($schemaPath), true) : [];
            $relationships = $schema['relationships'] ?? [];

            $relationshipMethods = '';
            foreach ($relationships as $rel) {
                $type = $rel['type'];
                $related = $rel['model'];
                $method = $rel['method'] ?? lcfirst($related);
                $foreignKey = isset($rel['foreign_key']) ? ", '{$rel['foreign_key']}'" : '';

                $relationshipMethods .= <<<EOD

    public function {$method}()
    {
        return \$this->{$type}({$related}::class{$foreignKey});
    }
EOD;
            }

            // Accessor: getFullNameAttribute
            $fieldNames = collect($fields)->pluck('name')->map('strtolower')->toArray();
            $fullNameAccessor = '';
            $appendsLine = '';

            if (in_array('first_name', $fieldNames) && in_array('last_name', $fieldNames)) {
                $fullNameAccessor = <<<EOD

    public function getFullNameAttribute()
    {
        return trim(\$this->first_name . ' ' . \$this->last_name);
    }
EOD;

                $appendsLine = "    protected \$appends = ['full_name'];\n\n";
            }

            // Inject all parts after class declaration
            $stub = preg_replace(
                '/(class\s+' . $model . '\s+extends\s+Model\s*\{)/',
                "$1\n\n{$fillableLine}{$appendsLine}{$castsLine}{$relationshipMethods}{$fullNameAccessor}\n",
                $stub
            );

            File::put($modelPath, $stub);
            $this->info("Model generated for {$model} with fillable, casts, relationships, accessors, and appends.");
            return true;
        } catch (\Exception $e) {
            $this->error('Failed to generate model: ' . $e->getMessage());
            return false;
        }
    }


    protected function generateRequest($model, $fields, $type = 'Update')
    {
        try {
            $className = "{$type}{$model}Request"; // 
            $namespace = "App\\Http\\Requests";
            $requestPath = app_path("Http/Requests/{$className}.php");

            $stubPath = base_path('stubs/request.stub');
            if (!File::exists($stubPath)) {
                $this->error('Request stub not found.');
                return false;
            }

            $stub = File::get($stubPath);

            $rulesArr = [];
            $messagesArr = [];

            foreach ($fields as $field) {
                $name = $field['name'];
                $label = ucfirst(str_replace('_', ' ', $name));

                // Start rule with required
                $rule = "required";

                // Add type-based rules
                switch ($field['type']) {
                    case 'email':
                        $rule .= '|email';
                        $messagesArr[] = "'{$name}.email' => 'The {$label} must be a valid email address.',";
                        break;
                    case 'integer':
                        $rule .= '|integer';
                        $messagesArr[] = "'{$name}.integer' => 'The {$label} must be an integer.',";
                        break;
                    case 'decimal':
                        $rule .= '|numeric';
                        $messagesArr[] = "'{$name}.numeric' => 'The {$label} must be a number.',";
                        break;
                    case 'text':
                    case 'string':
                        $rule .= '|string';
                        break;
                        // Add other types as needed
                }

                // Add max length if exists and type supports it
                if (in_array($field['type'], ['string', 'text'])) {
                    $max = $field['length'] ?? $field['max'] ?? null;
                    if ($max) {
                        $rule .= "|max:{$max}";
                        $messagesArr[] = "'{$name}.max' => 'The {$label} may not be greater than {$max} characters.',";
                    }
                }

                // Required message for all fields
                $messagesArr[] = "'{$name}.required' => 'The {$label} field is required.',";

                $rulesArr[] = "'{$name}' => '{$rule}',";
            }

            $rules = implode("\n            ", $rulesArr);
            $messages = implode("\n            ", $messagesArr);

            $stub = str_replace(
                ['{{ namespace }}', '{{ class }}', '{{ rules }}', '{{ messages }}'],
                [$namespace, $className, $rules, $messages],
                $stub
            );

            File::put($requestPath, $stub);

            $this->info("Request generated: {$className}");
            return true;
        } catch (\Exception $e) {
            $this->error('Failed to generate request: ' . $e->getMessage());
            Log::error('Failed to generate request: ' . $e->getMessage(), ['exception' => $e]);
            return false;
        }
    }

    protected function generateController($model, $fields)
    {
        try {
            $controllerName = "{$model}Controller";
            $controllerPath = app_path("Http/Controllers/{$controllerName}.php");

            $stubPath = base_path('stubs/controller.stub');
            if (!File::exists($stubPath)) {
                $this->error('Controller stub not found.');
                return false;
            }

            $stub = File::get($stubPath);

            $namespace = 'App\\Http\\Controllers';
            $tablePlural = Str::plural(Str::snake($model));

            // Detect foreign key relationships (e.g., 'author_id' => 'author')
            $relations = [];
            foreach ($fields as $field) {
                if (str_ends_with($field['name'], '_id')) {
                    $relation = Str::camel(str_replace('_id', '', $field['name']));
                    $relations[] = "'$relation'";
                }
            }

            $withRelations = count($relations) ? "with([" . implode(', ', $relations) . "])->" : "";

            $stub = str_replace(
                ['{{ namespace }}', '{{ model }}', '{{ table }}', '{{ withRelations }}'],
                [$namespace, $model, $tablePlural, $withRelations],
                $stub
            );

            File::put($controllerPath, $stub);

            $this->info("Custom controller generated: {$controllerName}");
            return true;
        } catch (\Exception $e) {
            $this->error('Failed to generate controller: ' . $e->getMessage());
            Log::error('Failed to generate controller: ' . $e->getMessage(), ['exception' => $e]);
            return false;
        }
    }

    protected function generateViews($model, $table, $fields)
    {
        try {
            $viewDir = resource_path("views/" . Str::snake($model));
            File::makeDirectory($viewDir, 0755, true, true);

            // Index View
            $indexStub = $this->getIndexViewStub($model, $table, $fields);
            File::put("{$viewDir}/index.blade.php", $indexStub);

            // Create View
            $createStub = $this->getCreateViewStub($model, $fields);
            File::put("{$viewDir}/create.blade.php", $createStub);

            // Edit View
            $editStub = $this->getEditViewStub($model, $fields);
            File::put("{$viewDir}/edit.blade.php", $editStub);

            // Show View
            $showStub = $this->getShowViewStub($model, $fields);
            File::put("{$viewDir}/show.blade.php", $showStub);

            $this->info("Views generated for {$model}");
            return true;
        } catch (\Exception $e) {
            $this->error('Failed to generate views: ' . $e->getMessage());
            Log::error('Failed to generate views: ' . $e->getMessage(), ['exception' => $e]);
            return false;
        }
    }

    protected function getIndexViewStub($model, $table, $fields)
    {
        $thead = "<th>S. No.</th>\n";
        $tbody = "<td>{{ \$loop->iteration }}</td>\n";

        foreach ($fields as $field) {
            $fieldName = $field['name'];
            $thead .= "<th>{{ __('labels.$fieldName') }}</th>\n";

            if (Str::endsWith($fieldName, '_id')) {
                $relation = Str::camel(str_replace('_id', '', $fieldName));
                $tbody .= "<td>{{ \$item->{$relation}->full_name ?? '-' }}</td>\n";
            } elseif (in_array($fieldName, ['summary', 'description'])) {
                $tbody .= "<td title=\"{{ \$item->$fieldName }}\">{{ Str::limit(\$item->$fieldName, 50) }}</td>\n";
            } elseif (Str::contains($fieldName, 'date')) {
                $tbody .= "<td>{{ optional(\$item->$fieldName)->format('Y-m-d') }}</td>\n";
            } else {
                $tbody .= "<td>{{ \$item->$fieldName }}</td>\n";
            }
        }

        $tablePlural = Str::plural($table);
        $tableId = strtolower($table) . '-table';
        $colspan = count($fields) + 2; // +2 for S.No. and Actions

        return <<<EOD
@extends('layouts.app')

@section('title', '{$model} List')

@push('styles')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
@endpush

@section('content')
    <div class="d-flex justify-content-between align-items-center mb-3 mt-5">
        <h1>{$model} List</h1>
        <a href="{{ route('{$tablePlural}.create') }}" class="btn btn-primary">Create {$model}</a>
    </div>

    <div class="table-responsive">
        <table id="{$tableId}" class="table table-bordered table-striped">
            <thead>
                <tr>
                    {$thead}
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @forelse(\${$tablePlural} as \$item)
                    <tr>
                        {$tbody}
                        <td>
                            <a href="{{ route('{$tablePlural}.show', \$item->id) }}" class="btn btn-sm btn-info">View</a>
                            <a href="{{ route('{$tablePlural}.edit', \$item->id) }}" class="btn btn-sm btn-warning">Edit</a>
                            <form action="{{ route('{$tablePlural}.destroy', \$item->id) }}" method="POST" class="d-inline" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="{$colspan}" class="text-center">No {$model}s found.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>
@endsection

@push('scripts')
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script>
        \$(document).ready(function () {
            \$('#{$tableId}').DataTable();
        });
    </script>
@endpush
EOD;
    }

    protected function getCreateViewStub($model, $fields)
    {
        $formFields = '';
        foreach ($fields as $field) {
            $name = $field['name'];
            $label = "{{ __('labels.$name') }}";

            // Determine input type
            if ($field['type'] === 'decimal') {
                $type = 'number';
            } elseif ($field['type'] === 'text') {
                $type = 'textarea';
            } elseif ($field['type'] === 'date') {
                $type = 'date'; // calendar input
            } else {
                $type = 'text';
            }

            if ($type === 'textarea') {
                $input = <<<HTML
            <textarea name="$name" id="$name" class="form-control @error('$name') is-invalid @enderror" placeholder="Enter $label" rows="4" cols="50">{{ old('$name') }}</textarea>
            @error('$name')
                <div class="invalid-feedback">{{ \$message }}</div>
            @enderror
            HTML;
            } else {
                $step = $field['type'] === 'decimal' ? ' step="0.01"' : '';
                $input = <<<HTML
            <input type="$type" name="$name" id="$name" class="form-control @error('$name') is-invalid @enderror"$step placeholder="Enter $label" value="{{ old('$name') }}">
            @error('$name')
                <div class="invalid-feedback">{{ \$message }}</div>
            @enderror
            HTML;
            }

            $formFields .= <<<EOD
            <div class="mb-3">
                <label for="$name" class="form-label">$label <span class="required">*</span></label>
                $input
            </div>

        EOD;
        }

        $table = Str::plural(Str::snake($model));

        return <<<EOD
        @extends('layouts.app')

        @section('title', 'Create {$model}')

        @section('content')
            <div class="mt-4">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h1>Create {$model}</h1>
                    <a href="{{ route('{$table}.index') }}" class="btn btn-secondary">← Back to List</a>
                </div>
                <form action="{{ route('{$table}.store') }}" method="POST" id="create-form">
                    @csrf
                    $formFields
                    <div class="d-flex justify-content-end gap-2">
                        <button type="reset" class="btn btn-outline-danger" id="clear-form">Cancel</button>
                        <button type="submit" class="btn btn-success">Save</button>
                    </div>
                </form>
            </div>
        <script>
            document.getElementById('clear-form').addEventListener('click', function () {
                const form = document.getElementById('create-form');
                form.querySelectorAll('input, textarea, select').forEach(input => {
                    if (input.type === 'checkbox' || input.type === 'radio') {
                        input.checked = false;
                    } else {
                        input.value = '';
                    }
                });
            });
        </script>
        @endsection
    EOD;
    }


    protected function getEditViewStub($model, $fields)
    {
        $formFields = '';
        foreach ($fields as $field) {
            $name = $field['name'];
            $label = "{{ __('labels.$name') }}";
            $type = $field['type'] == 'decimal' ? 'number' : ($field['type'] == 'text' ? 'textarea' : 'text');

            if ($type === 'textarea') {
                $input = <<<HTML
                <textarea name="$name" id="$name" class="form-control @error('$name') is-invalid @enderror" placeholder="Enter $label" rows="4" cols="50">{{ old('$name', \$item->$name) }}</textarea>
                @error('$name')
                    <div class="invalid-feedback">{{ \$message }}</div>
                @enderror
                HTML;
            } else {
                $step = $field['type'] == 'decimal' ? ' step="0.01"' : '';
                $input = <<<HTML
                <input type="$type" name="$name" id="$name" class="form-control @error('$name') is-invalid @enderror"$step placeholder="Enter $label" value="{{ old('$name', \$item->$name) }}">
                @error('$name')
                    <div class="invalid-feedback">{{ \$message }}</div>
                @enderror
                HTML;
            }

            $formFields .= <<<EOD
                <div class="mb-3">
                    <label for="$name" class="form-label">$label <span class="required">*</span></label>
                    $input
                </div>

            EOD;
        }

        $table = Str::plural(Str::snake($model));

        return <<<EOD
        @extends('layouts.app')

        @section('title', 'Edit {$model}')

        @section('content')
            <div class="mt-4">
                <div class="d-flex justify-content-between align-items-center mb-3">
                    <h1>Edit {$model}</h1>
                    <a href="{{ route('{$table}.index') }}" class="btn btn-secondary">← Back to List</a>
                </div>

                <form action="{{ route('{$table}.update', \$item->id) }}" method="POST" id="edit-form">
                    @csrf
                    @method('PUT')
                    $formFields
                    <div class="d-flex justify-content-end gap-2">
                        <button type="reset" class="btn btn-outline-danger" id="edit-clear-form">Cancel</button>
                        <button type="submit" class="btn btn-success">Update</button>
                    </div>
                </form>
            </div>
        <script>
            document.getElementById('edit-clear-form').addEventListener('click', function(e) {
                e.preventDefault(); // Prevent any default actions
                const form = document.getElementById('edit-form');
                form.querySelectorAll('input, textarea, select').forEach(input => {
                    if (input.type === 'hidden') return; // Skip hidden inputs, e.g., _method field
                    if (input.type === 'checkbox' || input.type === 'radio') {
                        input.checked = false;
                    } else {
                        input.value = '';
                    }
                });
            });
        </script>
        @endsection
        EOD;
    }

    protected function getShowViewStub($model, $fields)
    {
        $fieldsContent = '';
        foreach ($fields as $field) {
            $name = $field['name'];
            $fieldsContent .= "<p><strong>" . ucfirst($name) . ":</strong> {{ \$item->$name }}</p>\n    ";
        }

        $table = Str::plural(Str::snake($model));

        return <<<EOD
            @extends('layouts.app')

            @section('title', 'View {$model}')

            @section('content')
                <h1>View {$model}</h1>
                $fieldsContent
                <a href="{{ route('{$table}.index') }}" class="btn btn-secondary mt-3">Back to List</a>
            @endsection
            EOD;
    }

    protected function generateSeeder($model, $fields)
    {
        $namespace = "Database\\Seeders";
        $class = $model . "Seeder";

        // Build $fieldsString for seeder with faker data based on field type
        $fieldsString = '';
        foreach ($fields as $field) {
            $name = $field['name'];
            $type = strtolower($field['type'] ?? 'string');

            // Detect foreign key fields like 'author_id'
            if (str_ends_with($name, '_id')) {
                $relatedModel = ucfirst(Str::camel(str_replace('_id', '', $name)));
                $fieldsString .= "'$name' => \App\Models\\$relatedModel::inRandomOrder()->value('id') ?? 1,\n";
                continue;
            }

            switch ($type) {
                case 'decimal':
                case 'float':
                    $fieldsString .= "'$name' => \$faker->randomFloat(2, 1, 1000),\n";
                    break;

                case 'integer':
                case 'int':
                case 'bigint':
                    $fieldsString .= "'$name' => \$faker->numberBetween(1, 1000),\n";
                    break;

                case 'text':
                    $fieldsString .= "'$name' => \$faker->realText(100),\n";
                    break;

                case 'date':
                case 'datetime':
                case 'timestamp':
                    $fieldsString .= "'$name' => \$faker->date('Y-m-d'),\n";
                    break;

                case 'string':
                case 'varchar':
                default:
                    if ($name === 'isbn') {
                        $fieldsString .= "'$name' => \$faker->isbn13(),\n";
                    } else {
                        $fieldsString .= "'$name' => \$faker->sentence(3),\n";
                    }
                    break;
            }
        }

        $stub = <<<EOD
            <?php

            namespace $namespace;

            use Illuminate\Database\Seeder;
            use App\Models\\$model;
            use Faker\Factory as Faker;

            class $class extends Seeder
            {
                public function run()
                {
                    \$faker = Faker::create('en_US'); // Use US English locale

                    for (\$i = 0; \$i < 20; \$i++) {
                        $model::create([
            $fieldsString            ]);
                    }
                }
            }
            EOD;

        $seederPath = database_path("seeders/{$class}.php");
        file_put_contents($seederPath, $stub);

        $this->info("Seeder created: $seederPath");

        return true;
    }
}
